name: Gradle Build

on:
  push:
    branches:
      - dev

  pull_request:
    branches:
      - dev
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Make Gradle Wrapper Script Executable
        run: |
          sudo chmod +x gradlew
      - name: Setup Gradle and Build JAR
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: build -x test # As of now tests are not set up. So we'll ignore them

      - name: Get Branch Name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: himeko-artifacts-${{ steps.branch-name.outputs.current_branch }}
          path: build/libs/*.jar