name: Gradle Build

on: [ push, pull_request ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Validate Gradle Wrapper
      - uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle and Build JAR
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: build

      - name: Get Branch Name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - uses: actions/upload-artifact@v3
      - name: Upload JAR
        with:
          name: himeko-artifacts-${{ steps.branch-name.outputs.current_branch }}
          path: build/libs/*.jar